### ISSUE TITLE
Update Google Analytics tag to the latest tag

### ISSUE THREAD

**Issue by kilodalton** [MoTrPAC/motrpac-frontend#106]
Update current Google Analytics tag (analytics.js) to the latest tag (gtag.js)

>You can find the global site tag (gtag.js) in your Analytics account and implement it directly on your website. Find more information in our dynamic tagging guide. Note: if you already use Google Tag Manager no action is needed.

**Comment by kilodalton** [comment]
@jimmyzhen is this resolved now?

**Comment by jimmyzhen** [comment]
Yes. The changes have been merged into the `dev` branch recently.

**Comment by kilodalton** [comment]
resolved with PR #118
