### ISSUE TITLE
Phenotype Data Modeling

### ISSUE THREAD

**Issue by cteng585** [MoTrPAC/motrpac-frontend#116]
### Task: Figure out how DMAQC sends the BIC phenotype data so that it can be modeled and available via API to enable a more robust data hub and further integration with 3rd party communities (e.g. CFDE groups)

- There are two sets of phenotype data (PASS1A and PASS1B)
- PASS1A reflects phenotypes for acute exercise testing
- PASS1B reflects phenotypes for training

**Comment by jimmyzhen** [comment]
@cteng585 Is this task pertinent to the frontend app or more of a dev task?
