### ISSUE TITLE
Training Tab is Empty

### ISSUE THREAD

**Issue by cteng585** [MoTrPAC/motrpac-frontend#216]
When exploring differential expression data, the "Training" tab will be empty for certain searches, but there is no message to tell the user why the "Training" tab is empty. Some info here might enhance the user experience.

To replicate:
1. Go to the "Search differential expression data" tool
2. Type "BRCA1" as the gene name
3. Open the "Training" tab

**Comment by jimmyzhen** [comment]
@cteng585 thank you for reporting this issue. However, I was not able to reproduce it given your instructions.
![image](https://user-images.githubusercontent.com/6956310/214953962-2d9fe624-9f53-47eb-b685-961e9df34735.png)

**Comment by cteng585** [comment]
I haven't been able to reproduce the issue since reporting it. I think that we can consider this resolved since the issue isn't reproducible.
