### ISSUE TITLE
Clarify timewise vs training on the website

### ISSUE THREAD

**Issue by mihirsamdarshi** [MoTrPAC/motrpac-frontend#224]
On the differential tab and the gene-centric tab have pop up or hover preview infomration on what training and what timewise mean. Use slide 15 from this talk as an example: https://docs.google.com/presentation/d/1gdpewgnYEZx60nKAFtrlDAiLWwGJXT6-VKdbvi5uQmE/edit#slide=id.gc686c698e8_0_140

**Comment by jimmyzhen** [comment]
@mihirsamdarshi I have implemented the requested changes in the demo instance. Can you take a look and see whether the changes work for you? Thanks.
