### ISSUE TITLE
Searching a different gene doesn't reset all the filters

### ISSUE THREAD

**Issue by jimmyzhen** [MoTrPAC/motrpac-frontend#227]
For the DEA search and Gene-centric View components with existing search results and selected filters, searching a new/different gene does not reset the selected filters.

**Steps to reproduce:**
1. Go to differential abundance (DEA search) data
2. Search **BAG3**
3. Select **Heart** and **Liver** from tissue filters
4. Update results
5. Delete **BAG3** in the top text input field and enter **BRD2**
6. Click on the top **Search** button
7. Notice the  **Heart** and **Liver** filters still selected

**Comment by jimmyzhen** [comment]
@dhkatz12, I have addressed this issue and updated the demo site. Would you mind verifying it? Thank you.

**Comment by dhkatz12** [comment]
Looks good!
